export default {
  // Auth
  AUTH_REGISTER: 'auth/FETCH_REGISTER',
  AUTH_LOGIN: 'auth/FETCH_LOGIN',
  AUTH_FETCH_START: 'auth/FETCH_START',
  AUTH_FETCH_SUCCESS: 'auth/FETCH_SUCCESS',
  AUTH_FETCH_FINISH: 'auth/FETCH_FINISH',
  AUTH_FETCH_ERROR: 'auth/FETCH_ERROR',
 
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  // Global
  GLOBAL_FETCH_START: 'global/FETCH_START',
  GLOBAL_FETCH_FINISH: 'global/FETCH_FINISH',
  GLOBAL_FETCH_ERROR: 'global/FETCH_ERROR',

};